// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"
)

const createDocument = `-- name: CreateDocument :one
insert into documents (id, created_at, path, filename, filetype, locale, title, description, priority)
values (
	gen_random_UUID(),
	NOW(),
	$1, -- path
	$2, -- filename
	$3, -- filetype
	$4, -- locale
	$5, -- title
	$6, -- description
	$7 -- priority
	)
	returning id, created_at, path, filename, filetype, locale, title, description, priority
`

type CreateDocumentParams struct {
	Path        string
	Filename    string
	Filetype    string
	Locale      string
	Title       string
	Description string
	Priority    int32
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.Path,
		arg.Filename,
		arg.Filetype,
		arg.Locale,
		arg.Title,
		arg.Description,
		arg.Priority,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Path,
		&i.Filename,
		&i.Filetype,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.Priority,
	)
	return i, err
}
