// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocument = `-- name: CreateDocument :one
insert into documents (id, created_at, path, filename, filetype, locale, title, description, priority, active, category_id, hits)
values (
	gen_random_UUID(),
	NOW(),
	$1, -- path
	$2, -- filename
	$3, -- filetype
	$4, -- locale
	$5, -- title
	$6, -- description
	$7, -- priority
  $8, -- active
  $9, -- category_id
  0 -- hits
	)
	returning id, created_at, path, filename, filetype, locale, title, description, priority, active, category_id, hits
`

type CreateDocumentParams struct {
	Path        string
	Filename    string
	Filetype    string
	Locale      string
	Title       string
	Description string
	Priority    int32
	Active      bool
	CategoryID  uuid.UUID
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, createDocument,
		arg.Path,
		arg.Filename,
		arg.Filetype,
		arg.Locale,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Active,
		arg.CategoryID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Path,
		&i.Filename,
		&i.Filetype,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Active,
		&i.CategoryID,
		&i.Hits,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
delete from documents where id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
select id, created_at, path, filename, filetype, category_id, locale, title, description, priority, active from documents where id = $1
`

type GetDocumentRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Path        string
	Filename    string
	Filetype    string
	CategoryID  uuid.UUID
	Locale      string
	Title       string
	Description string
	Priority    int32
	Active      bool
}

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (GetDocumentRow, error) {
	row := q.db.QueryRowContext(ctx, getDocument, id)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Path,
		&i.Filename,
		&i.Filetype,
		&i.CategoryID,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Active,
	)
	return i, err
}

const getDocuments = `-- name: GetDocuments :many
select id, created_at, path, filename, filetype, category_id, locale, title, description, priority, active from documents
`

type GetDocumentsRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Path        string
	Filename    string
	Filetype    string
	CategoryID  uuid.UUID
	Locale      string
	Title       string
	Description string
	Priority    int32
	Active      bool
}

func (q *Queries) GetDocuments(ctx context.Context) ([]GetDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentsRow
	for rows.Next() {
		var i GetDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Path,
			&i.Filename,
			&i.Filetype,
			&i.CategoryID,
			&i.Locale,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocument = `-- name: UpdateDocument :one
update documents set  locale = $2, title = $3, description =$4, priority = $5, active = $6, category_id = $7 where id = $1 returning id, created_at, path, filename, filetype, locale, title, description, priority, active, category_id, hits
`

type UpdateDocumentParams struct {
	ID          uuid.UUID
	Locale      string
	Title       string
	Description string
	Priority    int32
	Active      bool
	CategoryID  uuid.UUID
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, updateDocument,
		arg.ID,
		arg.Locale,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Active,
		arg.CategoryID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Path,
		&i.Filename,
		&i.Filetype,
		&i.Locale,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Active,
		&i.CategoryID,
		&i.Hits,
	)
	return i, err
}
