// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document_categories.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocumentCategory = `-- name: CreateDocumentCategory :one
INSERT INTO document_categories(id, name, created_at, updated_at, active)
VALUES (
  gen_random_UUID(),
  $1, 
  NOW(),
  NOW(),
  true
  )
RETURNING id, name, created_at, updated_at, active
`

func (q *Queries) CreateDocumentCategory(ctx context.Context, name string) (DocumentCategory, error) {
	row := q.db.QueryRowContext(ctx, createDocumentCategory, name)
	var i DocumentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}

const deleteDocumentCategory = `-- name: DeleteDocumentCategory :exec
DELETE FROM document_categories WHERE id = $1
`

func (q *Queries) DeleteDocumentCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDocumentCategory, id)
	return err
}

const getDocumentCategories = `-- name: GetDocumentCategories :many
SELECT id, name, active, created_at, updated_at from document_categories
`

type GetDocumentCategoriesRow struct {
	ID        uuid.UUID
	Name      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetDocumentCategories(ctx context.Context) ([]GetDocumentCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDocumentCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentCategoriesRow
	for rows.Next() {
		var i GetDocumentCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentCategory = `-- name: GetDocumentCategory :one
SELECT id, name, active, created_at, updated_at from document_categories where id = $1
`

type GetDocumentCategoryRow struct {
	ID        uuid.UUID
	Name      string
	Active    bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetDocumentCategory(ctx context.Context, id uuid.UUID) (GetDocumentCategoryRow, error) {
	row := q.db.QueryRowContext(ctx, getDocumentCategory, id)
	var i GetDocumentCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentCategory = `-- name: UpdateDocumentCategory :one
UPDATE document_categories SET name = $2, updated_at = NOW(), active = $3 where id = $1 RETURNING id, name, created_at, updated_at, active
`

type UpdateDocumentCategoryParams struct {
	ID     uuid.UUID
	Name   string
	Active bool
}

func (q *Queries) UpdateDocumentCategory(ctx context.Context, arg UpdateDocumentCategoryParams) (DocumentCategory, error) {
	row := q.db.QueryRowContext(ctx, updateDocumentCategory, arg.ID, arg.Name, arg.Active)
	var i DocumentCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
	)
	return i, err
}
