// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Path        string
	Filename    string
	Filetype    string
	Locale      string
	Title       string
	Description string
	Priority    int32
	Visible     bool
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}
