// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	Path        string
	Filename    string
	Filetype    string
	Locale      string
	Title       string
	Description string
	Priority    int32
	Active      bool
	CategoryID  uuid.UUID
	Hits        sql.NullInt32
}

type DocumentCategory struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Active    bool
}

type RefreshToken struct {
	Token     string
	RevokedAt sql.NullTime
	CreatedAt time.Time
	ExpiresAt time.Time
	UserID    uuid.UUID
}

type User struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Email         string
	EmailVerified bool
	Password      string
	Active        bool
	LoginAttempts int32
}
