// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Path      string
	Filename  string
	Filetype  string
}

type DocumentMetadatum struct {
	ID          uuid.UUID
	DocumentID  uuid.UUID
	Locale      string
	Title       string
	Description sql.NullString
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}
